# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  # General file formatting and checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['--fix=lf']

  # JavaScript/Node.js specific hooks (warnings only for now)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        args: ['--max-warnings=100']  # Allow warnings but limit them
        additional_dependencies:
          - eslint@^8.0.0
          - eslint-config-standard@^17.0.0
          - eslint-plugin-import@^2.25.0
          - eslint-plugin-node@^11.1.0
          - eslint-plugin-promise@^6.0.0

  # Prettier for code formatting (check only, don't auto-fix for now)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, json, markdown, yaml]
        exclude: package-lock\.json|\.github/|script\.js|sw\.js
        args: ['--check']

  # Docker-related hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json